### ISSUE TITLE
No tarball for 3.9.3

### ISSUE THREAD

**Issue by ArchangeGabriel** [eoyilmaz/displaycal-py3#103]
While trying to upgrade the Arch package to 3.9.3, I could not find the source tarball on https://github.com/eoyilmaz/displaycal-py3/releases/tag/3.9.3.

I’ve use the provided tarball for previous releases, because trying to use the GitHub generated tarball results in:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1587, in <module>
    setup()
  File "setup.py", line 563, in setup
    lastmod_time = calendar.timegm(time.strptime(lastmod, "%Y-%m-%dT%H:%M:%SZ"))
  File "/usr/lib/python3.10/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '0000-00-00T00:00:00.0Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
* Getting dependencies for wheel...

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```
when using `build` and
```
/build/displaycal/src/displaycal-py3-3.9.3/setup.py:13: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import get_platform
Traceback (most recent call last):
  File "/build/displaycal/src/displaycal-py3-3.9.3/setup.py", line 1587, in <module>
    setup()
  File "/build/displaycal/src/displaycal-py3-3.9.3/setup.py", line 563, in setup
    lastmod_time = calendar.timegm(time.strptime(lastmod, "%Y-%m-%dT%H:%M:%SZ"))
  File "/usr/lib/python3.10/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '0000-00-00T00:00:00.0Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
```
when using setuptools.
```

**Comment by eoyilmaz** [comment]
Hey sorry for that, I've uploaded the tarball :+1:
