### ISSUE TITLE
Difficulties trying to install displaycal-py3

### ISSUE THREAD

**Issue by MrBananaPants** [eoyilmaz/displaycal-py3#123]
First things first, I'm a beginner with very little experience. Sorry if this is not the right place to post install issues / difficulties.

So I tried to install displaycal-py3 both the manual way (following [these](https://github.com/eoyilmaz/displaycal-py3#how-to-install) instructions) and with `pip3 install DisplayCAL`.
Both ways give me the same error (sorry for not using a code block, I had escaping issues):
![image](https://user-images.githubusercontent.com/41532982/170859726-34c7db71-5af0-4cb6-aa9d-a61b6124eb17.png)

Using `python3 setup.py build` also gives me an error. Can you help me with this?

**Comment by eoyilmaz** [comment]
can you please try the ``develop`` branch, that is, run ``git checkout develop`` (I should add this to installation instructions) before running the other instructions.

**Comment by eoyilmaz** [comment]
Actually I just release 3.9.5, you can install directly through pip by running:

```shell
pip install displaycal
```

**Comment by ignace72** [comment]
Hello, eoyilmaz.
Thanks for this new version.
With this method, it works for me too on a Manjaro Linux and in a virtual machine under openSUSE Leap.
However, I can't find the icon to make a launcher.
Can you help me?
Thank you.
Ignace.

**Comment by MrBananaPants** [comment]
Hi, I ran `pip3 install displaycal` and got the same error. Here's the full log:
```
joranvancoillie@iMac ~ % pip3 install displaycal
Collecting displaycal
  Downloading DisplayCAL-3.9.5.tar.gz (10.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 7.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dbus-python
  Using cached dbus-python-1.2.18.tar.gz (578 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Send2Trash in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from displaycal) (1.8.0)
Collecting PyChromecast
  Using cached PyChromecast-12.1.3-py2.py3-none-any.whl (62 kB)
Collecting numpy
  Using cached numpy-1.22.4-cp310-cp310-macosx_10_15_x86_64.whl (17.7 MB)
Collecting build
  Using cached build-0.8.0-py3-none-any.whl (17 kB)
Collecting distro
  Using cached distro-1.7.0-py3-none-any.whl (20 kB)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from displaycal) (2021.10.8)
Collecting Pillow
  Using cached Pillow-9.1.1-cp310-cp310-macosx_10_10_x86_64.whl (3.1 MB)
Collecting wxPython
  Using cached wxPython-4.1.1.tar.gz (66.0 MB)
  Preparing metadata (setup.py) ... done
Collecting zeroconf
  Using cached zeroconf-0.38.6-py3-none-any.whl (106 kB)
Collecting pep517>=0.9.1
  Using cached pep517-0.12.0-py2.py3-none-any.whl (19 kB)
Collecting packaging>=19.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting protobuf>=3.19.1
  Using cached protobuf-4.21.1-cp37-abi3-macosx_10_9_universal2.whl (483 kB)
Collecting casttube>=0.2.0
  Using cached casttube-0.2.1-py3-none-any.whl (6.5 kB)
Requirement already satisfied: ifaddr>=0.1.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from zeroconf->displaycal) (0.1.7)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from casttube>=0.2.0->PyChromecast->displaycal) (2.27.1)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->casttube>=0.2.0->PyChromecast->displaycal) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->casttube>=0.2.0->PyChromecast->displaycal) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->casttube>=0.2.0->PyChromecast->displaycal) (1.26.9)
Using legacy 'setup.py install' for dbus-python, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wxPython, since package 'wheel' is not installed.
Building wheels for collected packages: displaycal
  Building wheel for displaycal (pyproject.toml) ... done
  Created wheel for displaycal: filename=DisplayCAL-3.9.5-cp310-cp310-macosx_10_9_universal2.whl size=8893956 sha256=33f8459a3e2c99cca2570325d3b00e245987f3f00e1a9f41238b6493cbf5e0dd
  Stored in directory: /Users/joranvancoillie/Library/Caches/pip/wheels/07/79/c0/d13dbf7c421095db9db11d7ceb24237cbdf4f6bf7b8ebeca78
Successfully built displaycal
Installing collected packages: dbus-python, zeroconf, tomli, six, pyparsing, protobuf, Pillow, numpy, distro, wxPython, pep517, packaging, casttube, PyChromecast, build, displaycal
  Running setup.py install for dbus-python ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dbus-python did not run successfully.
  │ exit code: 1
  ╰─> [165 lines of output]
      running install
      running build
      creating /private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/build
      creating /private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/build/temp.macosx-10.9-universal2-3.10
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether gcc understands -c and -o together... yes
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking minix/config.h usability... no
      checking minix/config.h presence... no
      checking for minix/config.h... no
      checking whether it is safe to define __EXTENSIONS__... yes
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... /private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/build-aux/install-sh -c -d
      checking for gawk... no
      checking for mawk... no
      checking for nawk... no
      checking for awk... awk
      checking whether make sets $(MAKE)... yes
      checking whether make supports the include directive... yes (GNU style)
      checking whether UID '501' is supported by ustar format... yes
      checking whether GID '20' is supported by ustar format... yes
      checking how to create a ustar tar archive... gnutar
      checking dependency style of gcc... gcc3
      checking build system type... x86_64-apple-darwin21.6.0
      checking host system type... x86_64-apple-darwin21.6.0
      checking for native Windows host... no
      checking how to print strings... printf
      checking for a sed that does not truncate output... /usr/bin/sed
      checking for fgrep... /usr/bin/grep -F
      checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
      checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
      checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
      checking the name lister (/usr/bin/nm -B) interface... BSD nm
      checking whether ln -s works... yes
      checking the maximum length of command line arguments... 786432
      checking how to convert x86_64-apple-darwin21.6.0 file names to x86_64-apple-darwin21.6.0 format... func_convert_file_noop
      checking how to convert x86_64-apple-darwin21.6.0 file names to toolchain format... func_convert_file_noop
      checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
      checking for objdump... objdump
      checking how to recognize dependent libraries... pass_all
      checking for dlltool... no
      checking how to associate runtime and link libraries... printf %s\n
      checking for ar... ar
      checking for archiver @FILE support... no
      checking for strip... strip
      checking for ranlib... ranlib
      checking command to parse /usr/bin/nm -B output from gcc object... ok
      checking for sysroot... no
      checking for a working dd... /bin/dd
      checking how to truncate binary pipes... /bin/dd bs=4096 count=1
      checking for mt... no
      checking if : is a manifest tool... no
      checking for dsymutil... dsymutil
      checking for nmedit... nmedit
      checking for lipo... lipo
      checking for otool... otool
      checking for otool64... no
      checking for -single_module linker flag... yes
      checking for -exported_symbols_list linker flag... yes
      checking for -force_load linker flag... yes
      checking for dlfcn.h... yes
      checking for objdir... .libs
      checking if gcc supports -fno-rtti -fno-exceptions... yes
      checking for gcc option to produce PIC... -fno-common -DPIC
      checking if gcc PIC flag -fno-common -DPIC works... yes
      checking if gcc static flag -static works... no
      checking if gcc supports -c -o file.o... yes
      checking if gcc supports -c -o file.o... (cached) yes
      checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
      checking dynamic linker characteristics... darwin21.6.0 dyld
      checking how to hardcode library paths into programs... immediate
      checking whether stripping libraries is possible... yes
      checking if libtool supports shared libraries... yes
      checking whether to build shared libraries... yes
      checking whether to build static libraries... no
      checking for inline... inline
      checking for gawk... (cached) awk
      checking for python... /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
      checking for a version of Python >= '2.1.0'... yes
      checking for a version of Python >= '2.7'... yes
      checking for the distutils Python package... yes
      checking for Python include path... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10
      checking for Python library path... <stdin>:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <stdin>:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:3: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <stdin>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -L/Library/Frameworks/Python.framework/Versions/3.10/lib -lpython3.10
      checking for Python site-packages path... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
      checking python extra libraries... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -ldl   -framework CoreFoundation
      checking python extra linking flags... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.10/Python
      checking consistency of all components of python development environment... no
      configure: error: in `/private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/build/temp.macosx-10.9-universal2-3.10':
      configure: error:
        Could not link test program to Python. Maybe the main Python library has been
        installed in some non-standard library path. If so, pass it to configure,
        via the LIBS environment variable.
        Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
        ============================================================================
         ERROR!
         You probably have to install the development version of the Python package
         for your distribution.  The exact name of this package varies among them.
        ============================================================================
      
      See `config.log' for more details
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/setup.py", line 85, in <module>
          setup(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/command/install.py", line 568, in run
          self.run_command('build')
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/setup.py", line 56, in run
          subprocess.check_call([
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/configure', '--disable-maintainer-mode', 'PYTHON=/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10', '--prefix=/private/var/folders/xf/15k3h5d967b94lp7d36hplh40000gn/T/pip-install-bfb74unh/dbus-python_6da2e0bc61e74d198c52577a8eb7359a/build/temp.macosx-10.9-universal2-3.10/prefix']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dbus-python

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
joranvancoillie@iMac ~ % 
```

**Comment by eoyilmaz** [comment]
Yeah ``dbus`` installations create problems for some and I really don't know how to solve it. You may try downgrading your ``pip`` by the way, I remember some of the packages on my end were not installing properly with the latest ``pip`` (version 22.x.x) downgrading to pip 21.x.x solved my issues. But it could be totally irrelevant to that too.

**Comment by eoyilmaz** [comment]
Just ignore my previous comment for now, can you first install ``wheel`` with ``pip install wheel`` and then install DisplayCAL. It seems that there is no wheel installed and we probably need to update the installation instructions.

**Comment by Melluish** [comment]
OS: Fedora 36

Error when trying to install via pip:

`pip install DisplayCal`

I followed your last comment and installed wheel first:

`pip install wheel`

...but still got the attached error.
[pip-displaycal.log](https://github.com/eoyilmaz/displaycal-py3/files/8839822/pip-displaycal.log)

**Comment by eoyilmaz** [comment]
Because there is no:

```shell
WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
You should consider upgrading via the '***/bin/python -m pip install --upgrade pip' command.
```

I guess you run it with ``pip=22.x.x``. Try using version ``21.3.1`` it is working for me under Fedora 36.

**Comment by Melluish** [comment]
Thank you. I managed to get it installed, however when I start the calibration I get the following:

![image](https://user-images.githubusercontent.com/878650/172051838-1d706334-ea07-468c-bbd2-72ad35aa8006.png)

**Comment by eoyilmaz** [comment]
Okay, that's another issue, can you create a new ticket for that, I'm closing this one.
