### ISSUE TITLE
Problems gernerating metadata

### ISSUE THREAD

**Issue by hollowknut** [eoyilmaz/displaycal-py3#155]
While trying to run the scripts in requirements.txt a subprocess exits with an error while preparing the metadata.
Below is the error encountered and the output.

Collecting wxPython>=4.1.1
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rn4af9cs/wxpython_a6ccd52bdefe4f298a7fb8030f2399e1/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-rn4af9cs/wxpython_a6ccd52bdefe4f298a7fb8030f2399e1/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by p5k369** [comment]
Hey @hollowknut that has nothing to do with DisplayCal.
That error comes from installing wxPython-4.2.0. Some users reported that after installing `attrdict3` they also could install wxPython-4.2.0. See here: https://github.com/wxWidgets/Phoenix/issues/2225
If you can't get it to work you also could also set the requirement fix to `wxPython==4.1.1`

**Comment by ignace72** [comment]
Good evening to all.
This error happens with some GNU/Linux distributions (Mint, Ubuntu...).
To solve this error, you have to use an option that activates a deprecated option with the latest versions of pip.
Instead of using `pip install displaycal`, use `pip install displaycal --use-deprecated=backtrack-on-build-failures`.

**Comment by ignace72** [comment]
Hello everyone.
To install DisplayCAL with this error, I use this command:
`pip install displaycal --use-deprecated=backtrack-on-build-failures`
I don't know if this is the right solution, I just know that it works.

**Comment by p5k369** [comment]
That only works for you because you are using an outdated version of pip. `--use-deprecated=backtrack-on-build-failures`  has been removed with https://github.com/pypa/pip/pull/11241 as you can read here: https://pip.pypa.io/en/stable/news/#v22-2
Besides it is not the right way to deal with it. 
attrdict has been removed on purpose for every platform except windows from the wxPython requirements. So if that is a problem it should be fixed there. Meanwhile, the package could be pulled from DisplayCal requirements for better user experience like in #159 . That's not a parciluar heavy package.

**Comment by ignace72** [comment]
Thank you for your answer, p5k369.
Well, in doing :
```
pip install attrdict3
pip install displaycal
```
It works.
I tested on a Linux Mint but I guess on an Ubuntu it should work too.

**Comment by p5k369** [comment]
Temporary fixed in #159

**Comment by p5k369** [comment]
attrdict3 is needed to build wxPython 4.2.0 even if it is not used on the target system. See: https://github.com/wxWidgets/Phoenix/issues/2225
Therefore attrdict3 is now a dependency of DisplayCal as long as it is needed to build wxPython 4.2.0. Atm wxPython does not draw attrdict3 by itself.
