### ISSUE TITLE
PyPI installation aborts with error

### ISSUE THREAD

**Issue by starsforeveryone** [eoyilmaz/displaycal-py3#207]
Hello dear developers!

First: Thank you very, very much for continuing the legacy of DisplayCAL! To this day, the GNOME calibration tool does not work properly and nobody seems to care. Glad to see the software is continued in Python 3.

When trying to install DisplayCAL on the latest Fedora 37, I'm getting the following error message:

Command: sudo pip install displaycal

Output:

```
Collecting displaycal
  Using cached DisplayCAL-3.9.8.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      ['egg_info']
      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 1583, in <module>
          setup()
        File "setup.py", line 991, in setup
          from DisplayCAL.setup import setup
        File "/tmp/pip-install-zyei29qw/displaycal_27889b0fee934aaeb90e442829286e83/DisplayCAL/setup.py", line 70, in <module>
          from DisplayCAL.defaultpaths import autostart, autostart_home
        File "/tmp/pip-install-zyei29qw/displaycal_27889b0fee934aaeb90e442829286e83/DisplayCAL/defaultpaths.py", line 394, in <module>
          if isinstance(attr, (str, list)):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-zyei29qw/displaycal_27889b0fee934aaeb90e442829286e83/DisplayCAL/defaultpaths.py", line 298, in __getattribute__
          object.__getattribute__(self, "init")()
        File "/tmp/pip-install-zyei29qw/displaycal_27889b0fee934aaeb90e442829286e83/DisplayCAL/defaultpaths.py", line 375, in init
          XDG.set_translation(self)
        File "/tmp/pip-install-zyei29qw/displaycal_27889b0fee934aaeb90e442829286e83/DisplayCAL/defaultpaths.py", line 233, in set_translation
          obj.translation = gettext.translation(
                            ^^^^^^^^^^^^^^^^^^^^
      TypeError: translation() got an unexpected keyword argument 'codeset'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I just wanted to report that in the hope of finding a solution.

Kind regards!

**Comment by eoyilmaz** [comment]
Thank you for reporting this has been fixed with acc89e5 and 3.9.10 has been released to PyPI.

**Comment by starsforeveryone** [comment]
Thank you very much! Sadly, there's a new error now:

```
Collecting displaycal
  Using cached DisplayCAL-3.9.10.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting build
  Using cached build-0.9.0-py3-none-any.whl (17 kB)
Requirement already satisfied: certifi in /usr/lib/python3.11/site-packages (from displaycal) (2021.10.8)
Requirement already satisfied: distro in /usr/lib/python3.11/site-packages (from displaycal) (1.7.0)
Requirement already satisfied: numpy in /usr/lib64/python3.11/site-packages (from displaycal) (1.22.0)
Requirement already satisfied: Pillow in /usr/lib64/python3.11/site-packages (from displaycal) (9.2.0)
Collecting PyChromecast
  Using cached PyChromecast-13.0.1-py2.py3-none-any.whl (62 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3y4j3r_t/wxpython_c518ab61ce2346798d23f31a3769d9c6/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-3y4j3r_t/wxpython_c518ab61ce2346798d23f31a3769d9c6/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
        File "/usr/local/lib/python3.11/site-packages/attrdict/__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "/usr/local/lib/python3.11/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.11/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by starsforeveryone** [comment]
Don't want to nag! Just wanted to remind you that this bug was marked as "closed" although it's still there. :(

**Comment by eoyilmaz** [comment]
aah sorry, this is a new bug, if you can please report a new issue with the error message I'll look in to this week, it seems pretty trivial, tbh.

**Comment by starsforeveryone** [comment]
Done!
