### ISSUE TITLE
3.9.10: build failure with python 3.11

### ISSUE THREAD

**Issue by tgurr** [eoyilmaz/displaycal-py3#218]
While rebuilding the packages for python 3.11 on our distribution I run into the following error trying to build 3.9.10:

```
[...]
/usr/x86_64-pc-linux-gnu/bin/python3.11 -m build --wheel --no-isolation
* Getting dependencies for wheel...
/usr/x86_64-pc-linux-gnu/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
['egg_info']

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Traceback (most recent call last):
  File "/var/tmp/paludis/build/measurement-DisplayCAL-3.9.10/work/DisplayCAL-3.9.10/DisplayCAL/defaultpaths.py", line 234, in set_translation
    obj.translation = gettext.translation(
                      ^^^^^^^^^^^^^^^^^^^^
TypeError: translation() got an unexpected keyword argument 'codeset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/x86_64-pc-linux-gnu/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/x86_64-pc-linux-gnu/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/x86_64-pc-linux-gnu/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/x86_64-pc-linux-gnu/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/usr/x86_64-pc-linux-gnu/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1583, in <module>
  File "<string>", line 991, in setup
  File "/var/tmp/paludis/build/measurement-DisplayCAL-3.9.10/work/DisplayCAL-3.9.10/DisplayCAL/setup.py", line 70, in <module>
    from DisplayCAL.defaultpaths import autostart, autostart_home
  File "/var/tmp/paludis/build/measurement-DisplayCAL-3.9.10/work/DisplayCAL-3.9.10/DisplayCAL/defaultpaths.py", line 399, in <module>
    if isinstance(attr, (str, list)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/paludis/build/measurement-DisplayCAL-3.9.10/work/DisplayCAL-3.9.10/DisplayCAL/defaultpaths.py", line 303, in __getattribute__
    object.__getattribute__(self, "init")()
  File "/var/tmp/paludis/build/measurement-DisplayCAL-3.9.10/work/DisplayCAL-3.9.10/DisplayCAL/defaultpaths.py", line 380, in init
    XDG.set_translation(self)
  File "/var/tmp/paludis/build/measurement-DisplayCAL-3.9.10/work/DisplayCAL-3.9.10/DisplayCAL/defaultpaths.py", line 238, in set_translation
    obj.translation = gettext.translation(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/x86_64-pc-linux-gnu/lib/python3.11/gettext.py", line 516, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'xdg-user-dirs'

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =measurement/DisplayCAL-3.9.10:0::hardware --destination installed --replacing =measurement/DisplayCAL-3.9.7:0::installed --x-of-y 1 of 1:
  * When installing 'measurement/DisplayCAL-3.9.10:0::hardware' replacing { 'measurement/DisplayCAL-3.9.7:0::installed' }:
  * When running an ebuild command on 'measurement/DisplayCAL-3.9.10:0::hardware':
  * Install failed for 'measurement/DisplayCAL-3.9.10:0::hardware' (paludis::ActionFailedError)


!!! ERROR in measurement/DisplayCAL-3.9.10::hardware:
!!! In edo at line 1350
!!! /usr/x86_64-pc-linux-gnu/bin/python3.11 -m build --wheel --no-isolation failed
[...]
```
The first TypeError probably doesn't matter due to https://github.com/eoyilmaz/displaycal-py3/commit/f2ea3f28a8a170810af53b1501d5f505f9b4390d however it looks like it's running into another error afterwards.

**Comment by p5k369** [comment]
Hey @tgurr can you try to build with the dev-branch? I had to do some minor tweaks to get displaycal running with python 3.11.
The main branch will not run with python 3.11 because we set some limitations in the early porting phase.

**Comment by pgnd** [comment]
@p5k369 

> The main branch will not run with python 3.11 because we set some limitations in the early porting phase.

Just ran into this on a pip-install on Fedora37 + python 3.11.

_are_ those backports slated to move to main, and to PiPi?
or should we DIY build from dev branch for awhile ?

**Comment by p5k369** [comment]
At irregular intervals we merge the dev with the main branch and release a pypi package.
Do not install attrdict manually. You need attrdict3 for dependency reasons.

**Comment by eoyilmaz** [comment]
DisplayCAL 3.9.12 released a while ago... Closing this. Please reopen if 3.9.12 is not working for the same reason.
