### ISSUE TITLE
error on startup: "decoding str is not supported"

### ISSUE THREAD

**Issue by ywwg** [eoyilmaz/displaycal-py3#25]
```
Traceback (most recent call last):
  File "/home/owen/.local/lib/python3.9/site-packages/wx/lib/delayedresult.py", line 267, in wrapper
    result = workerFn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/DisplayCAL/worker.py", line 5526, in enumerate_displays_and_ports
    % (line[0], str(safe_str(value, enc), 
```

**Comment by eoyilmaz** [comment]
This should be fixed in 61059e70e97156804f6664ab4796e27936faa57f
