### ISSUE TITLE
Unable to profile in untethered mode

### ISSUE THREAD

**Issue by 3ll3d00d** [eoyilmaz/displaycal-py3#257]
NB: I'm unable to verify if this occurs in the published version because I can't run that locally due to https://github.com/eoyilmaz/displaycal-py3/issues/251

This occurs whether I'm running from my IDE (intellij/pycharm) or from a locally built version
running on develop (python 3.9 with wxPython 4.2.0)

set to Untethered mode
go to profile tab
click Profile Only

```
Traceback (most recent call last):
  File "/home/matt/dev/github/eoyilmaz/displaycal_venv_39/lib/python3.9/site-packages/wx/core.py", line 2346, in Notify
    self.notify()
  File "/home/matt/dev/github/eoyilmaz/displaycal_venv_39/lib/python3.9/site-packages/wx/core.py", line 3552, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/home/matt/dev/github/eoyilmaz/displaycal-py3/DisplayCAL/display_cal.py", line 11040, in just_profile
    self.worker.start_measurement(
  File "/home/matt/dev/github/eoyilmaz/displaycal-py3/DisplayCAL/worker.py", line 12544, in start_measurement
    self.start(
  File "/home/matt/dev/github/eoyilmaz/displaycal-py3/DisplayCAL/worker.py", line 14808, in start
    self.terminal = UntetheredFrame(
  File "/home/matt/dev/github/eoyilmaz/displaycal-py3/DisplayCAL/wxUntetheredFrame.py", line 51, in __init__
    super(UntetheredFrame, self).__init__(
  File "/home/matt/dev/github/eoyilmaz/displaycal-py3/DisplayCAL/wxwindows.py", line 938, in __init__
    wx.Frame.__init__(self, *args, **kwargs)
TypeError: Frame(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 2 has unexpected type 'MainFrame'
```

args contains both self & parent when it should just contain the parent

I think every other subclass of BaseFrame calls `BaseFrame.__init__` whereas this one was changed to `super(UntetheredFrame, self).__init__` (leaving the previous `BaseFrame.__init__` call commented out) which causes the problem
 
reverting this back to `BaseFrame.__init__` allows it to proceed without an exception

**Comment by 3ll3d00d** [comment]
there are other exceptions in this window so it would be good to know if untethered mode is confirmed to be working in this fork?

**Comment by 3ll3d00d** [comment]
used the flatpak to confirm the same problem occurs in the published release

**Comment by eoyilmaz** [comment]
Merged the PR, closing this issue.

**Comment by PaulDash** [comment]
Untethered profiling fails with a similar error in DisplayCAL version 3.9.17 with ArgyllCMS 3.4.1 attached to a Spyder X, which worked in other modes.

Error shows up after colorimeter calibration, with the _Untethered measurement_ window open.

Timer.Start(): argument 1 has unexpected type 'float'
<img width="417" height="260" alt="Image" src="https://github.com/user-attachments/assets/a08f1874-ace9-46cf-95f3-528782faffd7" />

**Comment by eoyilmaz** [comment]
@PaulDash this should be super easy to fix. I'll look into this most probably this week 👍 

I'm creating a new issue
