### ISSUE TITLE
Couldn't install profile

### ISSUE THREAD

**Issue by colneck** [eoyilmaz/displaycal-py3#283]
I finally managed to install DisplayCAL Py3 but now I am facing the next problem.. I can't install a profile on my MacBook Pro MAX M2 running OS Ventura 13.2.1.

If I choose to install for the current user I get an error:

Profil installieren
Traceback (most recent call last):
  File "/Users/jonaslink/displaycal_venv/lib/python3.9/site-packages/wx/lib/delayedresult.py", line 267, in wrapper
    result = workerFn(*args, **kwargs)
  File "/Users/jonaslink/displaycal_venv/lib/python3.9/site-packages/DisplayCAL/worker.py", line 1842, in __call__
    result = self.producer(*args, **kwargs)
  File "/Users/jonaslink/displaycal_venv/lib/python3.9/site-packages/DisplayCAL/worker.py", line 9408, in install_profile
    argyll_install = self._install_profile_argyll(
  File "/Users/jonaslink/displaycal_venv/lib/python3.9/site-packages/DisplayCAL/worker.py", line 9889, in _install_profile_argyll
    cmd, args = self.prepare_dispwin(None, profile_path, True)
  File "/Users/jonaslink/displaycal_venv/lib/python3.9/site-packages/DisplayCAL/worker.py", line 13957, in prepare_dispwin
    profile_tmp_path = os.path.join(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

If I choose to install for every User I get a sudo error. Can someone help? Is it a permission thing?

**Comment by richtong** [comment]
My user install works, but when I try a system install, then I get a sudo error, you can browse to the Displaycal directory and get the profile.

**Comment by jje1** [comment]
I had this problem too. I don't know how to fix the code, but I found a workaround - changing the profile naming pattern to a simpler format like just date and display name with hyphens.

You can change it in the profile section -> Profile Name.
I use this pattern: %dns-%Y-%m-%d %H-%M

**Comment by eoyilmaz** [comment]
This is fixed with 040e30f and will be released with 3.9.12

**Comment by eoyilmaz** [comment]
3.9.12 is released, fyi
