### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mistervi** [eoyilmaz/displaycal-py3#320]
I installed it with Pip and got this error at this end of the calibration process:

```
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
[Errno 2] No such file or directory: /var/folders/ck/3ch8q7b934997cmr26vygnvw0000gn/T/DisplayCAL-ug5dzu2x/S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX vs sRGB.wrl
[Errno 2] No such file or directory: /var/folders/ck/3ch8q7b934997cmr26vygnvw0000gn/T/DisplayCAL-ug5dzu2x/S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX vs ClayRGB1998.wrl
[Errno 2] No such file or directory: /var/folders/ck/3ch8q7b934997cmr26vygnvw0000gn/T/DisplayCAL-ug5dzu2x/S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX vs SMPTE431_P3.wrl
--------------------------------------------------------------------------------
Found display device matching model description at index #0
instrument_name: i1 DisplayPro, ColorMunki Display
display_name   : S27C900P
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/DisplayCAL/display_cal.py", line 11193, in profile_finish
    gamut_coverage = float(
                     ^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/DisplayCAL/display_cal.py", line 11193, in profile_finish
    gamut_coverage = float(
                     ^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/DisplayCAL/display_cal.py", line 11193, in profile_finish
    gamut_coverage = float(
                     ^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
Chargement des courbes d’étalonnage à partir du fichier…
/Users/vivien/Library/Application Support/DisplayCAL/storage/S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX/S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX.icc
… opération terminée.
--------------------------------------------------------------------------------
Installer le profil
--------------------------------------------------------------------------------
Session log: S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX

Répertoire de travail :
  /
   var/
    folders/
     ck/
      3ch8q7b934997cmr26vygnvw0000gn/
       T/
        DisplayCAL-yq0ry_ti/

Ligne de commandes :
  /Users/vivien/Applications/Argyll_V3.1.0/bin/dispwin
    -v
    -d1
    -I
    'S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX.icc'

About to open dispwin object on the display
About to install 'S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX.icc' as display's default profile
Installed 'S27C900P #1 2024-02-16 14-28 2.2 F-S 1xCurve+MTX.icc' and made it the default
About to destroy dispwin object
Dispwin: Warning - new_dispwin: Frame buffer depth 8 doesn't match VideoLUT 10
dispwin exitcode: 0
```

**Comment by eoyilmaz** [comment]
Okay, I confirm this bug and I can reproduce it.

**Comment by eoyilmaz** [comment]
Oh actually these are outputs of already handled errors, so there is nothing to fix here, and everything is working fine, closing this ticket...
