### ISSUE TITLE
Windows installation of DisplayCAL from PyPI fails. 

### ISSUE THREAD

**Issue by opopnever** [eoyilmaz/displaycal-py3#349]
Hi, it seems that PyPI has some hardcoded path which causes installation error on Windows:

`C:\Windows\System32>pip install DisplayCAL
Collecting DisplayCAL
  Using cached DisplayCAL-3.9.12.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      <string>:20: DeprecationWarning: 'msilib' is deprecated and slated for removal in Python 3.13
      ['egg_info']
      *** C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py egg_info
      using distutils
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-3dlut-maker.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-apply-profiles.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-curve-viewer.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-profile-info.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-scripting-client.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-synthprofile.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-testchart-editor.desktop
      desktopfile: C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\..\misc\displaycal-vrml-to-x3d-converter.desktop
      Traceback (most recent call last):
        File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1583, in <module>
        File "<string>", line 993, in setup
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-zntv6sdd\displaycal_fb0c93238214424485f0e3679ceb1e1a\DisplayCAL\setup.py", line 1624, in setup
          setup(**attrs)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 595, in add_defaults
          self.read_manifest()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\command\sdist.py", line 203, in read_manifest
          self.filelist.append(line)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 487, in append
          path = convert_path(item)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-iuz0qqkg\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/eoyilmaz/Documents/development/displaycal-py3/CHANGES.html' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by opopnever** [comment]
Already fixed - https://github.com/eoyilmaz/displaycal-py3/issues/334
