### ISSUE TITLE
An error occurred when I was installing via pip

### ISSUE THREAD

**Issue by kuangjy2** [eoyilmaz/displaycal-py3#355]
Good day!
I am trying to install the latest released version 3.9.12 via pip. But I got an error with the following message. My environment is Windows 10 22H2, Python 3.9.19 in the Anaconda.

```shell
(base) C:\Users\kuang>pip install DisplayCAL
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting DisplayCAL
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d2/28/f097487aa5a779863f311d44cafdbbe41d9ce9fe4089c805593d9dc0b96c/DisplayCAL-3.9.12.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      ['egg_info']
      *** D:\Programs\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py egg_info
      using distutils
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-3dlut-maker.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-apply-profiles.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-curve-viewer.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-profile-info.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-scripting-client.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-synthprofile.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-testchart-editor.desktop
      desktopfile: C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\..\misc\displaycal-vrml-to-x3d-converter.desktop
      Traceback (most recent call last):
        File "D:\Programs\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Programs\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Programs\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1583, in <module>
        File "<string>", line 993, in setup
        File "C:\Users\kuang\AppData\Local\Temp\pip-install-apjupfpw\displaycal_5d9d5ac38b634294b9787361bf76895c\DisplayCAL\setup.py", line 1624, in setup
          setup(**attrs)
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 595, in add_defaults
          self.read_manifest()
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\command\sdist.py", line 203, in read_manifest
          self.filelist.append(line)
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 487, in append
          path = convert_path(item)
        File "C:\Users\kuang\AppData\Local\Temp\pip-build-env-id64zu9p\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 132, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/eoyilmaz/Documents/development/displaycal-py3/CHANGES.html' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ownimage** [comment]
I have the same error ... I know that it is going to be fixed in 2.9.13 ... just wondered when that it going to be released to PyPI
If it is soon I will wait ... otherwise I will either try and install from source, or go back to the OEM Spyder calibrator software (yuk)

**Comment by ohnekopf** [comment]
same. is there a reason why the installation of this package has to be that complicated? from what i can tell my installation fails trying to build wxpython from source??

**Comment by eoyilmaz** [comment]
Oh this is a problem with the tarball that I created, it contains a path "/Users/eoyilmaz/Documents/development/displaycal-py3/CHANGES.html" which is specific to my development environment. I'll fix this in the next release (3.9.13).

**Comment by eoyilmaz** [comment]
Please try installing DisplayCAL using the instructions here: [How To Install (Windows)](https://github.com/eoyilmaz/displaycal-py3/tree/367-compiled-sucessfully-in-w10-py311-but-createprocess-fails-call-to-dispread-to-measure?tab=readme-ov-file#how-to-install-windows)

**Comment by eoyilmaz** [comment]
3.9.13 is out but it contains other bugs which are fixed in development version, you can running DisplayCAL by building it from source as explained in the [README](https://github.com/eoyilmaz/displaycal-py3?tab=readme-ov-file#installation-instructions-linux-and-macos).

**Comment by eoyilmaz** [comment]
Closing this as the original issue is solved.
