### ISSUE TITLE
Crash towards the end of the process

### ISSUE THREAD

**Issue by Kakupakat** [eoyilmaz/displaycal-py3#396]
**Versions (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Python Version: 3.11
 - ArgyllCMS Version: 3.2.0
 - DisplayCAL Version: 3.9.11 (fresh install)

**Describe the bug**
The program crashes after reading all the patches. While creating the profiles, I guess.

**To Reproduce**
Start the calibration, all patches are read, wait a short moment, crash.

**Expected behavior**
Start the calibration, all patches are read, wait a short moment, the profile is ready.

**Screenshots**
![DisplayCAL](https://github.com/user-attachments/assets/3d5ef422-03dc-485a-8e86-c00c6a026070)

**Additional context**
``` python
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
TypeError: TypeError('cannot use a string pattern on a bytes-like object')
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/wx/lib/delayedresult.py", line 267, in wrapper
    result = workerFn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/worker.py", line 1842, in __call__
    result = self.producer(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/worker.py", line 11602, in create_profile
    result = self.update_profile(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/worker.py", line 12276, in update_profile
    device_id = self.get_device_id(quirk=False, query=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/worker.py", line 8748, in get_device_id
    device_ids = colord.get_display_device_ids()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/colord.py", line 266, in get_display_device_ids
    display.properties.get("DeviceId") for display in get_display_devices()
                                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/colord.py", line 259, in get_display_devices
    return get_devices_by_kind("display")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/colord.py", line 254, in get_devices_by_kind
    for object_path in Colord.get_devices_by_kind(kind)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/DisplayCAL/util_dbus.py", line 67, in __call__
    return getattr(self._iface, self._method_name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/gi/overrides/Gio.py", line 349, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)

DisplayCAL: Uninhibited org.freedesktop.ScreenSaver
DisplayCAL: Uninhibited org.freedesktop.PowerManagement.Inhibit

```

**Comment by eoyilmaz** [comment]
DisplayCAL 3.9.11 is too old, please try with a newer version following the steps in [Prerequisites](https://github.com/eoyilmaz/displaycal-py3/?tab=readme-ov-file#prerequisites-linux-and-macos) & [Build From Srouce](https://github.com/eoyilmaz/displaycal-py3/?tab=readme-ov-file#build-from-source-makefile-workflow-linux--macos)

**Comment by Kakupakat** [comment]
I installed DisplayCAL 3.9.12 from an rpm and tried again. The result was the same.
Installing with [Build from Source](https://github.com/eoyilmaz/displaycal-py3/?tab=readme-ov-file#build-from-source-makefile-workflow-linux--macos) does not work.

**Comment by Kakupakat** [comment]
I installed 3.9.12, the newest available version, from an rpm and tried again. The result was exactly the same. 
Installing with [Build from Source](https://github.com/eoyilmaz/displaycal-py3/?tab=readme-ov-file#build-from-source-makefile-workflow-linux--macos) does not work. It always complains about not being able to build 'wheel' for 'wxPython'. I searched and tried all sorts of solutions, but the installation from source always fails.

**Comment by eoyilmaz** [comment]
Can you copy & paste the output where it is complaining about building wxPython.

**Comment by Kakupakat** [comment]
```
Finished command: build_wx (9m29.573s)
      Running command: build_py
      Checking for /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/bin/waf-2.1.2...
      "/home/kakupakat/bin/.venv/bin/python3" /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/bin/waf-2.1.2 --wx_config=/tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/wxbld/gtk3/wx-config --gtk3 --python="/home/kakupakat/bin/.venv/bin/python3" --out=build/waf/3.11/gtk3 configure build
      Setting top to                           : /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18
      Setting out to                           : /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/waf/3.11/gtk3
      Checking for 'gcc' (C compiler)          : /usr/bin/gcc
      Checking for 'g++' (C++ compiler)        : /usr/bin/g++
      Checking for program 'python'            : /home/kakupakat/bin/.venv/bin/python3
      Checking for python version >= 3.7.0     : 3.11.10
      python-config                            : /usr/bin/python3.11-config
      Asking python-config for pyext '--cflags --libs --ldflags' flags : yes
      Testing pyext configuration                                      : yes
      Finding libs for WX                                              : yes
      Finding libs for WXADV                                           : yes
      Finding libs for WXSTC                                           : yes
      Finding libs for WXHTML                                          : yes
      WARNING: Unable to find setup.h in /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/wxbld/gtk3/lib64/wx/include/gtk3-unicode-3.2, assuming wxUSE_GLCANVAS is not available.
      Finding libs for WXGL                                            : yes
      WARNING: Unable to find setup.h in /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/wxbld/gtk3/lib64/wx/include/gtk3-unicode-3.2, assuming wxUSE_WEBVIEW is not available.
      Finding libs for WXWEBVIEW                                       : yes
      Finding libs for WXXML                                           : yes
      Finding libs for WXXRC                                           : yes
      Finding libs for WXRICHTEXT                                      : yes
      WARNING: Unable to find setup.h in /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/wxbld/gtk3/lib64/wx/include/gtk3-unicode-3.2, assuming wxUSE_MEDIACTRL is not available.
      Finding libs for WXMEDIA                                         : yes
      Finding libs for WXRIBBON                                        : yes
      Finding libs for WXPROPGRID                                      : yes
      Finding libs for WXAUI                                           : yes
      'configure' finished successfully (1.533s)
      Waf: Entering directory `/tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/waf/3.11/gtk3'
      **** Compiler: gcc --version
           gcc (SUSE Linux) 14.2.0
           Copyright (C) 2024 Free Software Foundation, Inc.
           Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
           gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.
      [  1/939] Compiling sip/siplib/siplib.c
      [  2/939] Compiling sip/siplib/int_convertors.c
      [  3/939] Compiling sip/siplib/apiversions.c
      [  4/939] Compiling sip/siplib/qtlib.c
      [  5/939] Compiling sip/siplib/descriptors.c
      [  6/939] Compiling sip/siplib/threads.c
      [  7/939] Compiling sip/siplib/objmap.c
      [  8/939] Compiling sip/siplib/sip_array.c
      [  9/939] Compiling sip/siplib/voidptr.c
      [ 10/939] Compiling sip/cpp/sip_corewxListView.cpp
      In Datei, eingebunden von ../../../../ext/wxWidgets/include/wx/defs.h:45,
                       von ../../../../ext/wxWidgets/include/wx/wx.h:14,
                       von ../../../../wx/include/wxPython/wxpy_api.h:41,
                       von ../../../../sip/cpp/sipAPI_core.h:22089,
                       von ../../../../sip/cpp/sip_corewxListView.cpp:10:
      ../../../../ext/wxWidgets/include/wx/platform.h:159:10: schwerwiegender Fehler: wx/setup.h: Datei oder Verzeichnis nicht gefunden
        159 | #include "wx/setup.h"
            |          ^~~~~~~~~~~~
      Kompilierung beendet.
      
      Waf: Leaving directory `/tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/waf/3.11/gtk3'
      Build failed
       -> task in '_core' failed with exit status 1 (run with -v to display more information)
      Command '"/home/kakupakat/bin/.venv/bin/python3" /tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/bin/waf-2.1.2 --wx_config=/tmp/pip-install-ojiidprt/wxpython_d96684bfea3e427c86c9b161c2532d18/build/wxbld/gtk3/wx-config --gtk3 --python="/home/kakupakat/bin/.venv/bin/python3" --out=build/waf/3.11/gtk3 configure build ' failed with exit code 1.
      Finished command: build_py (0m5.787s)
      Finished command: build (9m35.361s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.
      
      "/home/kakupakat/bin/.venv/bin/python3" -u build.py build
      Command '"/home/kakupakat/bin/.venv/bin/python3" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxPython
Failed to build wxPython
ERROR: Could not build wheels for wxPython, which is required to install pyproject.toml-based projects
```
There you go. Hope it helps.

**Comment by eoyilmaz** [comment]
hmm... yeah, I think it is because you are building `wxPython` with `gcc 14` and this is known to be not working also not compatible with Python 3.11. I don't know how easy it is to install `gcc 12`, but there is your solution.

**Comment by vazmiguel** [comment]
When running displaycal in Arch Linux I bumped into this exact error. 
For Arch Linux, perhaps there is a similar fix for other distros, the issue seems to have been fixed after installing colord/colord-kde:

sudo pacman -S colord
sudo pacman -S colord-kde

**Comment by eoyilmaz** [comment]
Recently we had another [issue ticket](https://github.com/eoyilmaz/displaycal-py3/issues/484) reported for the same `DBus` error message, the reported error is related to the fact that the system running DisplayCAL has no Power Management installed (possibly using Wayland), thus the `org.freedesktop.ScreenSaver` and `org.freedesktop.PowerManagement.Inhibit` are not available and DisplayCAL is just reporting it as a warning. We made it clear that it is a warning with #484 

On the other hand, the `TypeError: TypeError('cannot use a string pattern on a bytes-like object')` should have already been fixed with the more recent versions of DisplayCAL.

DisplayCAL 3.9.16 will be released soon, please use that version and report in another issue ticket again.

**Comment by eoyilmaz** [comment]
DisplayCAL 3.9.16 has been released 👍
