### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#421]
Add support for Python 3.13. Currently it is not possible to build under Python 3.13:

```shell
eoyilmaz@Erkans-MacBook-Pro displaycal-py3 % make build

--- build: Building ---
echo -e "\n\033[36m--- build: Local install into virtualenv '.venv' ---\033[0m\n";

--- build: Local install into virtualenv '.venv' ---

source ./.venv/bin/activate; \
        echo -e "\n\033[36m--- build: Using python interpretter '`which python`' ---\033[0m\n"; \
        pip install -r requirements.txt; \
        pip install -r requirements-dev.txt; \
        python -m build;

--- build: Using python interpretter '/Users/eoyilmaz/Documents/development/displaycal-py3/.venv/bin/python' ---

Ignoring comtypes: markers 'sys_platform == "win32"' don't match your environment
Ignoring dbus-python: markers 'sys_platform == "linux"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring wmi: markers 'sys_platform == "win32"' don't match your environment
Collecting build (from -r requirements.txt (line 1))
  Using cached build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi (from -r requirements.txt (line 2))
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting distro (from -r requirements.txt (line 5))
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting future (from -r requirements.txt (line 6))
  Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting numpy (from -r requirements.txt (line 7))
  Using cached numpy-2.1.2-cp313-cp313-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting Pillow (from -r requirements.txt (line 8))
  Using cached pillow-10.4.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting protobuf (from -r requirements.txt (line 9))
  Using cached protobuf-5.28.2-cp38-abi3-macosx_10_9_universal2.whl.metadata (592 bytes)
Collecting PyChromecast (from -r requirements.txt (line 10))
  Using cached PyChromecast-14.0.4-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting qtpy (from -r requirements.txt (line 12))
  Downloading QtPy-2.4.1-py3-none-any.whl.metadata (12 kB)
Collecting Send2Trash (from -r requirements.txt (line 13))
  Using cached Send2Trash-1.8.3-py3-none-any.whl.metadata (4.0 kB)
Collecting wxPython>=4.2.2 (from -r requirements.txt (line 15))
  Using cached wxPython-4.2.2-cp313-cp313-macosx_10_13_universal2.whl.metadata (3.0 kB)
Collecting zeroconf (from -r requirements.txt (line 16))
  Using cached zeroconf-0.135.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.1 kB)
Collecting packaging>=19.1 (from build->-r requirements.txt (line 1))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pyproject_hooks (from build->-r requirements.txt (line 1))
  Using cached pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Collecting casttube>=0.2.0 (from PyChromecast->-r requirements.txt (line 10))
  Using cached casttube-0.2.1-py3-none-any.whl.metadata (960 bytes)
Collecting six (from wxPython>=4.2.2->-r requirements.txt (line 15))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting ifaddr>=0.1.7 (from zeroconf->-r requirements.txt (line 16))
  Using cached ifaddr-0.2.0-py3-none-any.whl.metadata (4.9 kB)
Collecting requests (from casttube>=0.2.0->PyChromecast->-r requirements.txt (line 10))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests->casttube>=0.2.0->PyChromecast->-r requirements.txt (line 10))
  Using cached charset_normalizer-3.4.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->casttube>=0.2.0->PyChromecast->-r requirements.txt (line 10))
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->casttube>=0.2.0->PyChromecast->-r requirements.txt (line 10))
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Using cached build-1.2.2.post1-py3-none-any.whl (22 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading future-1.0.0-py3-none-any.whl (491 kB)
Using cached numpy-2.1.2-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
Using cached pillow-10.4.0-cp313-cp313-macosx_11_0_arm64.whl (3.4 MB)
Using cached protobuf-5.28.2-cp38-abi3-macosx_10_9_universal2.whl (414 kB)
Using cached PyChromecast-14.0.4-py2.py3-none-any.whl (76 kB)
Downloading QtPy-2.4.1-py3-none-any.whl (93 kB)
Using cached Send2Trash-1.8.3-py3-none-any.whl (18 kB)
Using cached wxPython-4.2.2-cp313-cp313-macosx_10_13_universal2.whl (30.4 MB)
Using cached zeroconf-0.135.0-cp313-cp313-macosx_14_0_arm64.whl (4.8 MB)
Using cached casttube-0.2.1-py3-none-any.whl (6.5 kB)
Using cached ifaddr-0.2.0-py3-none-any.whl (12 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.0-cp313-cp313-macosx_11_0_arm64.whl (119 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: ifaddr, zeroconf, urllib3, six, Send2Trash, pyproject_hooks, protobuf, Pillow, packaging, numpy, idna, future, distro, charset-normalizer, certifi, wxPython, requests, qtpy, build, casttube, PyChromecast
Successfully installed Pillow-10.4.0 PyChromecast-14.0.4 Send2Trash-1.8.3 build-1.2.2.post1 casttube-0.2.1 certifi-2024.8.30 charset-normalizer-3.4.0 distro-1.9.0 future-1.0.0 idna-3.10 ifaddr-0.2.0 numpy-2.1.2 packaging-24.1 protobuf-5.28.2 pyproject_hooks-1.2.0 qtpy-2.4.1 requests-2.32.3 six-1.16.0 urllib3-2.2.3 wxPython-4.2.2 zeroconf-0.135.0
Ignoring py2exe: markers 'sys_platform == "win32"' don't match your environment
Collecting black (from -r requirements-dev.txt (line 1))
  Using cached black-24.10.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting coverage (from -r requirements-dev.txt (line 2))
  Downloading coverage-7.6.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting darglint (from -r requirements-dev.txt (line 3))
  Using cached darglint-1.8.1-py3-none-any.whl.metadata (19 kB)
Collecting flake8 (from -r requirements-dev.txt (line 4))
  Using cached flake8-7.1.1-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting flake8-bugbear (from -r requirements-dev.txt (line 5))
  Using cached flake8_bugbear-24.8.19-py3-none-any.whl.metadata (32 kB)
Collecting flake8-docstrings (from -r requirements-dev.txt (line 6))
  Using cached flake8_docstrings-1.7.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting flake8-import-order (from -r requirements-dev.txt (line 7))
  Using cached flake8_import_order-0.18.2-py2.py3-none-any.whl.metadata (8.3 kB)
Collecting flake8-mutable (from -r requirements-dev.txt (line 8))
  Using cached flake8_mutable-1.2.0-py3-none-any.whl
Collecting flake8-pep3101 (from -r requirements-dev.txt (line 9))
  Using cached flake8_pep3101-2.1.0-py3-none-any.whl.metadata (23 kB)
Collecting flake8-spellcheck (from -r requirements-dev.txt (line 10))
  Using cached flake8_spellcheck-0.28.0-py3-none-any.whl.metadata (3.6 kB)
Collecting matplotlib (from -r requirements-dev.txt (line 11))
  Using cached matplotlib-3.9.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting ppdir (from -r requirements-dev.txt (line 12))
  Using cached ppdir-0.1.0-py3-none-any.whl.metadata (953 bytes)
Collecting py2app (from -r requirements-dev.txt (line 13))
  Using cached py2app-0.28.8-py2.py3-none-any.whl.metadata (63 kB)
Collecting pyglet (from -r requirements-dev.txt (line 15))
  Using cached pyglet-2.0.18-py3-none-any.whl.metadata (7.9 kB)
Collecting pytest (from -r requirements-dev.txt (line 16))
  Using cached pytest-8.3.3-py3-none-any.whl.metadata (7.5 kB)
Collecting pytest-cov (from -r requirements-dev.txt (line 17))
  Using cached pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting pytest-github-actions-annotate-failures (from -r requirements-dev.txt (line 18))
  Using cached pytest_github_actions_annotate_failures-0.2.0-py3-none-any.whl.metadata (3.1 kB)
Collecting pytest-xdist (from -r requirements-dev.txt (line 19))
  Using cached pytest_xdist-3.6.1-py3-none-any.whl.metadata (4.3 kB)
Collecting snowballstemmer (from -r requirements-dev.txt (line 20))
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting twine (from -r requirements-dev.txt (line 21))
  Using cached twine-5.1.1-py3-none-any.whl.metadata (3.5 kB)
Collecting yappi (from -r requirements-dev.txt (line 22))
  Using cached yappi-1.6.0.tar.gz (59 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting wheel (from -r requirements-dev.txt (line 23))
  Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
Collecting click>=8.0.0 (from black->-r requirements-dev.txt (line 1))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting mypy-extensions>=0.4.3 (from black->-r requirements-dev.txt (line 1))
  Using cached mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: packaging>=22.0 in ./.venv/lib/python3.13/site-packages (from black->-r requirements-dev.txt (line 1)) (24.1)
Collecting pathspec>=0.9.0 (from black->-r requirements-dev.txt (line 1))
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Collecting platformdirs>=2 (from black->-r requirements-dev.txt (line 1))
  Using cached platformdirs-4.3.6-py3-none-any.whl.metadata (11 kB)
Collecting mccabe<0.8.0,>=0.7.0 (from flake8->-r requirements-dev.txt (line 4))
  Using cached mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting pycodestyle<2.13.0,>=2.12.0 (from flake8->-r requirements-dev.txt (line 4))
  Using cached pycodestyle-2.12.1-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting pyflakes<3.3.0,>=3.2.0 (from flake8->-r requirements-dev.txt (line 4))
  Using cached pyflakes-3.2.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting attrs>=19.2.0 (from flake8-bugbear->-r requirements-dev.txt (line 5))
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting pydocstyle>=2.1 (from flake8-docstrings->-r requirements-dev.txt (line 6))
  Using cached pydocstyle-6.3.0-py3-none-any.whl.metadata (3.7 kB)
Collecting setuptools (from flake8-import-order->-r requirements-dev.txt (line 7))
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements-dev.txt (line 11))
  Using cached contourpy-1.3.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements-dev.txt (line 11))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->-r requirements-dev.txt (line 11))
  Using cached fonttools-4.54.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (163 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->-r requirements-dev.txt (line 11))
  Using cached kiwisolver-1.4.7-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.13/site-packages (from matplotlib->-r requirements-dev.txt (line 11)) (2.1.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.13/site-packages (from matplotlib->-r requirements-dev.txt (line 11)) (10.4.0)
Collecting pyparsing>=2.3.1 (from matplotlib->-r requirements-dev.txt (line 11))
  Using cached pyparsing-3.2.0-py3-none-any.whl.metadata (5.0 kB)
Collecting python-dateutil>=2.7 (from matplotlib->-r requirements-dev.txt (line 11))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting colorama>=0.4.3 (from ppdir->-r requirements-dev.txt (line 12))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting altgraph>=0.17.3 (from py2app->-r requirements-dev.txt (line 13))
  Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting modulegraph>=0.19.6 (from py2app->-r requirements-dev.txt (line 13))
  Using cached modulegraph-0.19.6-py2.py3-none-any.whl.metadata (14 kB)
Collecting macholib>=1.16.2 (from py2app->-r requirements-dev.txt (line 13))
  Using cached macholib-1.16.3-py2.py3-none-any.whl.metadata (11 kB)
Collecting iniconfig (from pytest->-r requirements-dev.txt (line 16))
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting pluggy<2,>=1.5 (from pytest->-r requirements-dev.txt (line 16))
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting execnet>=2.1 (from pytest-xdist->-r requirements-dev.txt (line 19))
  Using cached execnet-2.1.1-py3-none-any.whl.metadata (2.9 kB)
Collecting pkginfo>=1.8.1 (from twine->-r requirements-dev.txt (line 21))
  Using cached pkginfo-1.11.2-py3-none-any.whl.metadata (11 kB)
Collecting readme-renderer>=35.0 (from twine->-r requirements-dev.txt (line 21))
  Using cached readme_renderer-44.0-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: requests>=2.20 in ./.venv/lib/python3.13/site-packages (from twine->-r requirements-dev.txt (line 21)) (2.32.3)
Collecting requests-toolbelt!=0.9.0,>=0.8.0 (from twine->-r requirements-dev.txt (line 21))
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: urllib3>=1.26.0 in ./.venv/lib/python3.13/site-packages (from twine->-r requirements-dev.txt (line 21)) (2.2.3)
Collecting importlib-metadata>=3.6 (from twine->-r requirements-dev.txt (line 21))
  Using cached importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting keyring>=15.1 (from twine->-r requirements-dev.txt (line 21))
  Using cached keyring-25.4.1-py3-none-any.whl.metadata (20 kB)
Collecting rfc3986>=1.4.0 (from twine->-r requirements-dev.txt (line 21))
  Using cached rfc3986-2.0.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting rich>=12.0.0 (from twine->-r requirements-dev.txt (line 21))
  Using cached rich-13.9.2-py3-none-any.whl.metadata (18 kB)
Collecting pkginfo>=1.8.1 (from twine->-r requirements-dev.txt (line 21))
  Using cached pkginfo-1.10.0-py3-none-any.whl.metadata (11 kB)
Collecting zipp>=3.20 (from importlib-metadata>=3.6->twine->-r requirements-dev.txt (line 21))
  Using cached zipp-3.20.2-py3-none-any.whl.metadata (3.7 kB)
Collecting jaraco.classes (from keyring>=15.1->twine->-r requirements-dev.txt (line 21))
  Using cached jaraco.classes-3.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting jaraco.functools (from keyring>=15.1->twine->-r requirements-dev.txt (line 21))
  Using cached jaraco.functools-4.1.0-py3-none-any.whl.metadata (2.9 kB)
Collecting jaraco.context (from keyring>=15.1->twine->-r requirements-dev.txt (line 21))
  Using cached jaraco.context-6.0.1-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib->-r requirements-dev.txt (line 11)) (1.16.0)
Collecting nh3>=0.2.14 (from readme-renderer>=35.0->twine->-r requirements-dev.txt (line 21))
  Using cached nh3-0.2.18-cp37-abi3-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl.metadata (1.7 kB)
Collecting docutils>=0.21.2 (from readme-renderer>=35.0->twine->-r requirements-dev.txt (line 21))
  Using cached docutils-0.21.2-py3-none-any.whl.metadata (2.8 kB)
Collecting Pygments>=2.5.1 (from readme-renderer>=35.0->twine->-r requirements-dev.txt (line 21))
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests>=2.20->twine->-r requirements-dev.txt (line 21)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests>=2.20->twine->-r requirements-dev.txt (line 21)) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.13/site-packages (from requests>=2.20->twine->-r requirements-dev.txt (line 21)) (2024.8.30)
Collecting markdown-it-py>=2.2.0 (from rich>=12.0.0->twine->-r requirements-dev.txt (line 21))
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.0.0->twine->-r requirements-dev.txt (line 21))
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting more-itertools (from jaraco.classes->keyring>=15.1->twine->-r requirements-dev.txt (line 21))
  Using cached more_itertools-10.5.0-py3-none-any.whl.metadata (36 kB)
Using cached black-24.10.0-cp313-cp313-macosx_11_0_arm64.whl (1.4 MB)
Downloading coverage-7.6.3-cp313-cp313-macosx_11_0_arm64.whl (207 kB)
Using cached darglint-1.8.1-py3-none-any.whl (120 kB)
Using cached flake8-7.1.1-py2.py3-none-any.whl (57 kB)
Using cached flake8_bugbear-24.8.19-py3-none-any.whl (35 kB)
Using cached flake8_docstrings-1.7.0-py2.py3-none-any.whl (5.0 kB)
Using cached flake8_import_order-0.18.2-py2.py3-none-any.whl (15 kB)
Using cached flake8_pep3101-2.1.0-py3-none-any.whl (16 kB)
Using cached flake8_spellcheck-0.28.0-py3-none-any.whl (333 kB)
Using cached matplotlib-3.9.2-cp313-cp313-macosx_11_0_arm64.whl (7.8 MB)
Using cached ppdir-0.1.0-py3-none-any.whl (3.4 kB)
Using cached py2app-0.28.8-py2.py3-none-any.whl (835 kB)
Using cached pyglet-2.0.18-py3-none-any.whl (941 kB)
Using cached pytest-8.3.3-py3-none-any.whl (342 kB)
Using cached pytest_cov-5.0.0-py3-none-any.whl (21 kB)
Using cached pytest_github_actions_annotate_failures-0.2.0-py3-none-any.whl (5.5 kB)
Using cached pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Using cached twine-5.1.1-py3-none-any.whl (38 kB)
Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
Using cached altgraph-0.17.4-py2.py3-none-any.whl (21 kB)
Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached contourpy-1.3.0-cp313-cp313-macosx_11_0_arm64.whl (251 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached execnet-2.1.1-py3-none-any.whl (40 kB)
Using cached fonttools-4.54.1-cp313-cp313-macosx_11_0_arm64.whl (2.2 MB)
Using cached importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Using cached keyring-25.4.1-py3-none-any.whl (38 kB)
Using cached kiwisolver-1.4.7-cp313-cp313-macosx_11_0_arm64.whl (63 kB)
Using cached macholib-1.16.3-py2.py3-none-any.whl (38 kB)
Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Using cached modulegraph-0.19.6-py2.py3-none-any.whl (34 kB)
Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Using cached pkginfo-1.10.0-py3-none-any.whl (30 kB)
Using cached platformdirs-4.3.6-py3-none-any.whl (18 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached pycodestyle-2.12.1-py2.py3-none-any.whl (31 kB)
Using cached pydocstyle-6.3.0-py3-none-any.whl (38 kB)
Using cached pyflakes-3.2.0-py2.py3-none-any.whl (62 kB)
Using cached pyparsing-3.2.0-py3-none-any.whl (106 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached readme_renderer-44.0-py3-none-any.whl (13 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)
Using cached rich-13.9.2-py3-none-any.whl (242 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
Using cached docutils-0.21.2-py3-none-any.whl (587 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached nh3-0.2.18-cp37-abi3-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl (1.4 MB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached zipp-3.20.2-py3-none-any.whl (9.2 kB)
Using cached jaraco.classes-3.4.0-py3-none-any.whl (6.8 kB)
Using cached jaraco.context-6.0.1-py3-none-any.whl (6.8 kB)
Using cached jaraco.functools-4.1.0-py3-none-any.whl (10 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached more_itertools-10.5.0-py3-none-any.whl (60 kB)
Building wheels for collected packages: yappi
  Building wheel for yappi (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for yappi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-14.0-arm64-cpython-313
      copying yappi/yappi.py -> build/lib.macosx-14.0-arm64-cpython-313
      running build_ext
      building '_yappi' extension
      creating build/temp.macosx-14.0-arm64-cpython-313/yappi
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/eoyilmaz/Documents/development/displaycal-py3/.venv/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c yappi/_yappi.c -o build/temp.macosx-14.0-arm64-cpython-313/yappi/_yappi.o
      yappi/_yappi.c:1288:5: error: call to undeclared function '_PyEval_SetProfile'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       1288 |     _PyEval_SetProfile(ts, _yapp_callback, NULL);
            |     ^
      yappi/_yappi.c:1288:5: note: did you mean 'PyEval_SetProfile'?
      /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/ceval.h:5:18: note: 'PyEval_SetProfile' declared here
          5 | PyAPI_FUNC(void) PyEval_SetProfile(Py_tracefunc, PyObject *);
            |                  ^
      yappi/_yappi.c:1302:5: error: call to undeclared function '_PyEval_SetProfile'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       1302 |     _PyEval_SetProfile(ts, NULL, NULL);
            |     ^
      2 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yappi
Failed to build yappi
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (yappi)
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - pywin32; platform_system=='Windows'
  - setuptools
  - wxpython; platform_system=='Windows'
* Getting build dependencies for sdist...
Trying to get git version information...
Trying to get git information...
Generating __version__.py
Version 3.9.13
['egg_info']
*** /Users/eoyilmaz/Documents/development/displaycal-py3/.venv/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py egg_info
using distutils
warning: no files found matching 'MANIFEST'
warning: no files found matching 'use-distutils'
warning: no files found matching '_in_process.py'
warning: no files found matching '_in_process.cfg'
warning: no files found matching 'dist/net.displaycal.DisplayCAL.appdata.xml'
warning: no files found matching 'DisplayCAL/quirk.json'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.backup' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
* Building sdist...
Trying to get git version information...
Trying to get git information...
Generating __version__.py
Version 3.9.13
Traceback (most recent call last):
  File "/Users/eoyilmaz/Documents/development/displaycal-py3/.venv/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
    ~~~~^^
  File "/Users/eoyilmaz/Documents/development/displaycal-py3/.venv/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eoyilmaz/Documents/development/displaycal-py3/.venv/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/8l/xy1__ym94nn35x86xyg56xq80000gn/T/build-env-r9pdvbpq/lib/python3.13/site-packages/setuptools/build_meta.py", line 432, in build_sdist
    return self._build_with_temp_dir(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        ['sdist', '--formats', 'gztar'], '.tar.gz', sdist_directory, config_settings
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/private/var/folders/8l/xy1__ym94nn35x86xyg56xq80000gn/T/build-env-r9pdvbpq/lib/python3.13/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "/private/var/folders/8l/xy1__ym94nn35x86xyg56xq80000gn/T/build-env-r9pdvbpq/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 1588, in <module>
  File "<string>", line 662, in setup
  File "/Users/eoyilmaz/Documents/development/displaycal-py3/DisplayCAL/localization.py", line 6, in <module>
    from DisplayCAL.config import data_dirs, defaults, getcfg, storage
  File "/Users/eoyilmaz/Documents/development/displaycal-py3/DisplayCAL/config.py", line 45, in <module>
    from DisplayCAL.wxaddons import wx
  File "/Users/eoyilmaz/Documents/development/displaycal-py3/DisplayCAL/wxaddons.py", line 9, in <module>
    from DisplayCAL.wxfixes import wx, GenButton, PlateButton, get_dialogs
  File "/Users/eoyilmaz/Documents/development/displaycal-py3/DisplayCAL/wxfixes.py", line 27, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

ERROR Backend subprocess exited when trying to invoke build_sdist
make: *** [build] Error 1
```

**Comment by eoyilmaz** [comment]
Okay so, `yappi` is failing to build and I don't know if we require it.

**Comment by eoyilmaz** [comment]
Seems to be DisplayCAL is working fine with Python 3.13.0 after 3e2664e at least under MacOS Sonoma 14.7.
