### ISSUE TITLE
Windows installer version of DisplayCAL seems lacking pyglet

### ISSUE THREAD

**Issue by Headcrabed** [eoyilmaz/displaycal-py3#442]
When exiting installer version of DisplayCAL 3.9.14, an error window popped:
![图片](https://github.com/user-attachments/assets/cb04255e-2b7d-49cc-af9c-e23f4d90e990)

log here:
```
NoneType: None
NoneType: None
NoneType: None
NoneType: None
NoneType: None
NoneType: None
Exception ignored in atexit callback: <function _delete_audio_driver at 0x0000019C120153A0>
Traceback (most recent call last):
  File "pyglet\media\drivers\__init__.pyc", line 79, in _delete_audio_driver
  File "pyglet\media\__init__.pyc", line 48, in <module>
  File "pyglet\media\player.pyc", line 11, in <module>
ModuleNotFoundError: No module named 'pyglet.gl'
NoneType: None
NoneType: None
NoneType: None
NoneType: None
Exception ignored in atexit callback: <function _delete_audio_driver at 0x00000270FEA4D300>
Traceback (most recent call last):
  File "pyglet\media\drivers\__init__.pyc", line 79, in _delete_audio_driver
  File "pyglet\media\__init__.pyc", line 48, in <module>
  File "pyglet\media\player.pyc", line 11, in <module>
ModuleNotFoundError: No module named 'pyglet.gl'
Exception ignored in atexit callback: <function _delete_audio_driver at 0x00000278F9985300>
Traceback (most recent call last):
  File "pyglet\media\drivers\__init__.pyc", line 79, in _delete_audio_driver
  File "pyglet\media\__init__.pyc", line 48, in <module>
  File "pyglet\media\player.pyc", line 11, in <module>
ModuleNotFoundError: No module named 'pyglet.gl'
Exception ignored in atexit callback: <function _delete_audio_driver at 0x0000019D7E545300>
Traceback (most recent call last):
  File "pyglet\media\drivers\__init__.pyc", line 79, in _delete_audio_driver
  File "pyglet\media\__init__.pyc", line 48, in <module>
  File "pyglet\media\player.pyc", line 11, in <module>
ModuleNotFoundError: No module named 'pyglet.gl'
NoneType: None

```

**Comment by Headcrabed** [comment]
Seems fixed, so close this.
