### ISSUE TITLE
[Windows] Assertion failed on launch

### ISSUE THREAD

**Issue by Acrivec** [eoyilmaz/displaycal-py3#447]
**Describe the bug**
![image](https://github.com/user-attachments/assets/6c302f1b-2b1e-4ca6-bcef-899712894c04)
after OK:
![image](https://github.com/user-attachments/assets/921cd2ed-b370-4288-8022-99e8760dcfa2)
after 2-3 similar OK:
![image](https://github.com/user-attachments/assets/1fa3f42f-a345-4fbe-b9c6-618012437c8c)
after OK:
![image](https://github.com/user-attachments/assets/1512e069-c362-4cee-ba16-45cfab605bf5)
Then it's stuck on loading screen
![image](https://github.com/user-attachments/assets/7acc9b10-2ab9-43d1-92f0-882a420700c3)
..untill killing process.

**To Reproduce**
First launch after installing.

**Versions (please complete the following information):**
 - OS: Windows 11 22631.4317
 - Python Version: 3.10.6 installed
 - ArgyllCMS Version: [e.g. 3.0.2, 3.1.0, 3.2.0]
 - DisplayCAL Version: [e.g. 3.9.12]

**Additional context**
[Window Title]
DisplayCAL

[Main Instruction]
C++ assertion "which == State_Normal" failed at ..\..\src\msw\anybutton.cpp(819) in wxAnyButton::DoSetBitmap(): Must set normal bitmap with the new size first

[Content]
```cmd
Traceback (most recent call last):
  File "DisplayCAL\xh_filebrowsebutton.pyc", line 28, in DoCreateResource
  File "DisplayCAL\wxwindows.pyc", line 3185, in __init__
  File "wx\lib\filebrowsebutton.pyc", line 75, in __init__
  File "DisplayCAL\wxwindows.pyc", line 3334, in createDialog
  File "DisplayCAL\wxwindows.pyc", line 3310, in createBrowseButton
  File "DisplayCAL\wxfixes.pyc", line 1200, in __init__
  File "DisplayCAL\wxfixes.pyc", line 990, in set_bitmap_labels
wx._core.wxAssertionError: C++ assertion "which == State_Normal" failed at ..\..\src\msw\anybutton.cpp(819) in wxAnyButton::DoSetBitmap(): Must set normal bitmap with the new size first


WARNING: Your version of wxPython (4.2.1) is outdated and no longer supported. You should consider updating to wxPython 4.2.2 or newer.

[OK]
```
then
```cmd
[Window Title]
DisplayCAL

[Main Instruction]
C++ assertion "which == State_Normal" failed at ..\..\src\msw\anybutton.cpp(819) in wxAnyButton::DoSetBitmap(): Must set normal bitmap with the new size first

[Content]
Traceback (most recent call last):
  File "DisplayCAL\xh_filebrowsebutton.pyc", line 28, in DoCreateResource
  File "DisplayCAL\wxwindows.pyc", line 3185, in __init__
  File "wx\lib\filebrowsebutton.pyc", line 75, in __init__
  File "DisplayCAL\wxwindows.pyc", line 3334, in createDialog
  File "DisplayCAL\wxwindows.pyc", line 3310, in createBrowseButton
  File "DisplayCAL\wxfixes.pyc", line 1200, in __init__
  File "DisplayCAL\wxfixes.pyc", line 990, in set_bitmap_labels
wx._core.wxAssertionError: C++ assertion "which == State_Normal" failed at ..\..\src\msw\anybutton.cpp(819) in wxAnyButton::DoSetBitmap(): Must set normal bitmap with the new size first


WARNING: Your version of wxPython (4.2.1) is outdated and no longer supported. You should consider updating to wxPython 4.2.2 or newer.

[OK]```
after 2-3x ok
```cmd
[Window Title]
DisplayCAL

[Main Instruction]
C++ assertion ""Assert failure"" failed at ..\..\src\common\sizer.cpp(678) in wxSizerItem::SetDimension(): can't set size of uninitialized sizer item

[Content]
Traceback (most recent call last):
  File "wx\core.pyc", line 3427, in <lambda>
  File "DisplayCAL\display_cal.pyc", line 19520, in setup_frame
  File "DisplayCAL\display_cal.pyc", line 1874, in __init__
  File "DisplayCAL\display_cal.pyc", line 2079, in init_frame
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\common\sizer.cpp(678) in wxSizerItem::SetDimension(): can't set size of uninitialized sizer item


WARNING: Your version of wxPython (4.2.1) is outdated and no longer supported. You should consider updating to wxPython 4.2.2 or newer.

**Comment by KubaT1987** [comment]
I get the exact same error messages.

Windows 11 Pro 23H2 and 24H2.

**Comment by Hubedge** [comment]
Running it in compatible mode (Windows 7) seem to workaround the issue

**Comment by eoyilmaz** [comment]
This has been fixed with 6c95735 in #507
