### ISSUE TITLE
DisplayCAL 3.9.14 for Windows Can't Install profile as system default

### ISSUE THREAD

**Issue by FQDianYan** [eoyilmaz/displaycal-py3#452]
**Describe the bug**
Can't Install profile as system default

**To Reproduce**
1. Loading Setting...
2. Install profile
3. Install profile as system default

DisplayCAL-apply-profiles.log output

```shell
Traceback (most recent call last):
  File "DisplayCAL\profile_loader.pyc", line 195, in setup_profile_loader_task
  File "DisplayCAL\taskscheduler.pyc", line 359, in create_task
  File "DisplayCAL\taskscheduler.pyc", line 264, in write_xml
  File "DisplayCAL\taskscheduler.pyc", line 271, in __str__
  File "DisplayCAL\taskscheduler.pyc", line 271, in __str__
  File "DisplayCAL\taskscheduler.pyc", line 271, in __str__
  [Previous line repeated 489 more times]
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DisplayCAL\main.pyc", line 550, in main
  File "DisplayCAL\main.pyc", line 537, in _main
  File "DisplayCAL\profile_loader.pyc", line 3987, in main
  File "DisplayCAL\profile_loader.pyc", line 225, in setup_profile_loader_task
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte
```

**Screenshots**

![03](https://github.com/user-attachments/assets/e1081d39-d9b0-4eb1-bf00-296e3616c6ea)

**Versions (please complete the following information):**
 - OS: Windows 11 24H2 10.0.26100.2033 x86_64
 - Python Version: 3.11
 - ArgyllCMS Version: 3.3.0
 - DisplayCAL Version: 3.9.14

**Comment by eoyilmaz** [comment]
Thanks for the report, this should be fixed with 3969791 and will be released with DisplayCAL 3.9.16.

**Comment by eoyilmaz** [comment]
DisplayCAL 3.9.16 has been released 👍
