### ISSUE TITLE
Windows Error after poweroff or restart

### ISSUE THREAD

**Issue by FQDianYan** [eoyilmaz/displaycal-py3#455]
**Describe the bug**
DisplayCAL 3.9.14 for Windows Error when poweroff or restart compoter

**To Reproduce**
1. Poweroff or Restart Computer
2. See error

DisplayCAL-apply-profiles.log output

```shell
Traceback (most recent call last):
  File "DisplayCAL\profile_loader.pyc", line 195, in setup_profile_loader_task
  File "DisplayCAL\taskscheduler.pyc", line 359, in create_task
  File "DisplayCAL\taskscheduler.pyc", line 264, in write_xml
  File "DisplayCAL\taskscheduler.pyc", line 271, in __str__
  File "DisplayCAL\taskscheduler.pyc", line 271, in __str__
  File "DisplayCAL\taskscheduler.pyc", line 271, in __str__
  [Previous line repeated 489 more times]
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DisplayCAL\main.pyc", line 550, in main
  File "DisplayCAL\main.pyc", line 537, in _main
  File "DisplayCAL\profile_loader.pyc", line 3987, in main
  File "DisplayCAL\profile_loader.pyc", line 225, in setup_profile_loader_task
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte
NoneType: None
NoneType: None
```

**Screenshots**
![屏幕截图 2024-10-26 134021](https://github.com/user-attachments/assets/68e2be0e-bb6e-4032-a55c-70f3ba0dde6e)

**Versions (please complete the following information):**

 - OS: Windows 11 24H2 10.0.26100.2033 x86_64
 - Python Version: 3.11
 - ArgyllCMS Version: 3.3.0
 - DisplayCAL Version: 3.9.14

**Comment by eoyilmaz** [comment]
Fixed and will be released soon with DisplayCAL 3.9.16.

**Comment by eoyilmaz** [comment]
DisplayCAL 3.9.16 has been released 👍
