### ISSUE TITLE
Broken on ArchLinux

### ISSUE THREAD

**Issue by LethalManBoob** [eoyilmaz/displaycal-py3#474]
```shell
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib/python3.13/site-packages/wx/core.py", line 3427, in         │
│ <lambda>                                                                     │
│     lambda event: event.callable(*event.args, **event.kw) )                  │
│                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^                    │
│   File "/usr/lib/python3.13/site-packages/DisplayCAL/display_cal.py", line   │
│ 19520, in setup_frame                                                        │
│     app.frame = MainFrame(self.worker)                                       │
│                 ~~~~~~~~~^^^^^^^^^^^^^                                       │
│   File "/usr/lib/python3.13/site-packages/DisplayCAL/display_cal.py", line   │
│ 1876, in __init__                                                            │
│     self.set_child_ctrls_as_attrs(self)                                      │
│     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^                                      │
│   File "/usr/lib/python3.13/site-packages/DisplayCAL/wxwindows.py", line     │
│ 2346, in set_child_ctrls_as_attrs                                            │
│     for child in parent.GetAllChildren():                                    │
│                  ~~~~~~~~~~~~~~~~~~~~~^^                                     │
│   File "/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py", line 101, │
│ in GetAllChildren                                                            │
│     children = [child for child in self.GetChildren() if child not in skip]  │
│                                    ~~~~~~~~~~~~~~~~^^                        │
│ TypeError: 'WindowList_iterator' object is not iterable                      │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by jarrard** [comment]
yeah, been this way for well over a couple weeks.  No solution found! 

'WindowList_iterator' object is not iterable

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/wx/core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
                  ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/DisplayCAL/display_cal.py", line 19520, in setup_frame
    app.frame = MainFrame(self.worker)
                ~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/DisplayCAL/display_cal.py", line 1876, in __init__
    self.set_child_ctrls_as_attrs(self)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/DisplayCAL/wxwindows.py", line 2346, in set_child_ctrls_as_attrs
    for child in parent.GetAllChildren():
                 ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py", line 101, in GetAllChildren
    children = [child for child in self.GetChildren() if child not in skip]
                                   ~~~~~~~~~~~~~~~~^^
TypeError: 'WindowList_iterator' object is not iterable

**Comment by NohanMV** [comment]
Python 3.13 and wxPython issues.

Can be fixed by modifying manually **/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** and **/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** by encapsulating the mentionned method call in a `list(foo.GetChildren()) `as to make the return types iterable through a list type cast :

**/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** replace line 101 with : 
`children = [child for child in list(self.GetChildren()) if child not in skip]`

**/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** replace line 1027 with :
`for window in list(wx.GetTopLevelWindows())`

**Comment by jarrard** [comment]
Thanks I'll check it out.

**Comment by LethalManBoob** [comment]
> Python 3.13 and wxPython issues.
> 
> Can be fixed by modifying manually **/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** and **/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** by encapsulating the mentionned method call in a `list(foo.GetChildren()) `as to make the return types iterable through a list type cast :
> 
> **/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** replace line 101 with : `children = [child for child in list(self.GetChildren()) if child not in skip]`
> 
> **/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** replace line 1027 with : `for window in list(wx.GetTopLevelWindows())`

works for me!

**Comment by yuriykorchmar** [comment]
I have the same issue on Garuda Linux.

> Python 3.13 and wxPython issues.
> 
> Can be fixed by modifying manually **/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** and **/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** by encapsulating the mentionned method call in a `list(foo.GetChildren()) `as to make the return types iterable through a list type cast :
> 
> **/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** replace line 101 with : `children = [child for child in list(self.GetChildren()) if child not in skip]`
> 
> **/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** replace line 1027 with : `for window in list(wx.GetTopLevelWindows())`

This fix doesn't work for me.

**Comment by lepolau** [comment]
Same issue for me with Fedora 41. The solution works. Thanks a lot.


> Python 3.13 and wxPython issues.
> 
> Can be fixed by modifying manually **/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** and **/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** by encapsulating the mentionned method call in a `list(foo.GetChildren()) `as to make the return types iterable through a list type cast :
> 
> **/usr/lib/python3.13/site-packages/DisplayCAL/wxaddons.py** replace line 101 with : `children = [child for child in list(self.GetChildren()) if child not in skip]`
> 
> **/usr/lib/python3.13/site-packages/DisplayCAL/wxfixes.py** replace line 1027 with : `for window in list(wx.GetTopLevelWindows())`

**Comment by eoyilmaz** [comment]
This has been fixed with 9ec4902 as a part of #414

**Comment by FabriceSalvaire** [comment]
Fedora 42 is broken

```
Name            : DisplayCAL
Version         : 3.9.14
Release         : 3.fc42
Source          : DisplayCAL-3.9.14-3.fc42.src.rpm
From repository : fedora
URL             : https://github.com/eoyilmaz/displaycal-py3
Vendor          : Fedora Project
```
