### ISSUE TITLE
Measurement report raises ``Could not extract calibration data from the profile.`` error message and exit

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#65]
After a successful calibration/profiling session. Running ``Measurement report...`` raises ``Could not extract calibration data from the profile.`` error message and exit. There is no error message on the console.

![image](https://user-images.githubusercontent.com/1786804/159808317-62cc4a3f-4dc1-4abf-a7f8-acf638ffef98.png)

**Comment by eoyilmaz** [comment]
Searching for the original language string of ``cal_extraction_failed`` revealed 3 places that this error is raised. Adding ``traceback.print_exc()`` statements to the ``try...except`` blocks, revealed the following error message:

```python
Measurement report...
Traceback (most recent call last):
  File "/home/erkan.yilmaz/PycharmProjects/DisplayCAL/venv/lib/python3.9/site-packages/DisplayCAL-3.8.9.3-py3.9-linux-x86_64.egg/DisplayCAL/display_cal.py", line 9163, in measurement_report
    cal = extract_cal_from_profile(calprof, cal_path, False)
  File "/home/erkan.yilmaz/PycharmProjects/DisplayCAL/venv/lib/python3.9/site-packages/DisplayCAL-3.8.9.3-py3.9-linux-x86_64.egg/DisplayCAL/argyll_cgats.py", line 243, in extract_cal_from_profile
    cgats = vcgt_to_cal(profile)
  File "/home/erkan.yilmaz/PycharmProjects/DisplayCAL/venv/lib/python3.9/site-packages/DisplayCAL-3.8.9.3-py3.9-linux-x86_64.egg/DisplayCAL/argyll_cgats.py", line 560, in vcgt_to_cal
    context = cgats.add_data({"DESCRIPTOR": b"Argyll Device Calibration State"})
  File "/home/erkan.yilmaz/PycharmProjects/DisplayCAL/venv/lib/python3.9/site-packages/DisplayCAL-3.8.9.3-py3.9-linux-x86_64.egg/DisplayCAL/CGATS.py", line 1133, in add_data
    context = self.add_data(self.file_identifier)  # create root element
  File "/home/erkan.yilmaz/PycharmProjects/DisplayCAL/venv/lib/python3.9/site-packages/DisplayCAL-3.8.9.3-py3.9-linux-x86_64.egg/DisplayCAL/CGATS.py", line 1133, in add_data
    context = self.add_data(self.file_identifier)  # create root element
  File "/home/erkan.yilmaz/PycharmProjects/DisplayCAL/venv/lib/python3.9/site-packages/DisplayCAL-3.8.9.3-py3.9-linux-x86_64.egg/DisplayCAL/CGATS.py", line 1133, in add_data
    context = self.add_data(self.file_identifier)  # create root element
  [Previous line repeated 981 more times]
  File "/home/erkan.yilmaz/PycharmProjects/DisplayCAL/venv/lib/python3.9/site-packages/DisplayCAL-3.8.9.3-py3.9-linux-x86_64.egg/DisplayCAL/CGATS.py", line 1022, in add_data
    if self.type == b"DATA":
RecursionError: maximum recursion depth exceeded in comparison
```

So, something is calling itself over and over again...
