### ISSUE TITLE
wxSynthICCFrame raises ``KeyError``

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/displaycal-py3#97]
Sille an issue:

```shell
displaycal-synthprofile
Acquired lock file: <DisplayCAL.main.AppLock object at 0x7ff1bf47f2b0>
displaycal-synthprofile 3.9.2 2022-04-30T16:13:37Z
manjaro 21.2.6 Qonos x86_64
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
Faulthandler 
wxPython 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
Encoding: utf-8
File system encoding: utf-8
Loading /home/christian/.config/DisplayCAL/DisplayCAL.ini
Existing client using port 15411
listening
writing to lock file: port: 43455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 549, in main
    _main(module, name, applockfilename)
  File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 536, in _main
    main()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1347, in main
    app.TopWindow = SynthICCFrame()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 146, in __init__
    self.update_controls()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1219, in update_controls
    self.update_trc_controls()
  File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py", line 1300, in update_trc_controls
    self.profile_class_ctrl.GetStringSelection() == self.profile_classes["scnr"]
KeyError: 'scnr'
┌──────────────────────────────────────────────────────────────────────────────┐
│ Traceback (most recent call last):                                           │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 549, in  │
│ main                                                                         │
│     _main(module, name, applockfilename)                                     │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/main.py", line 536, in  │
│ _main                                                                        │
│     main()                                                                   │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1347, in main                                                           │
│     app.TopWindow = SynthICCFrame()                                          │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 146, in __init__                                                        │
│     self.update_controls()                                                   │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1219, in update_controls                                                │
│     self.update_trc_controls()                                               │
│   File "/usr/lib/python3.10/site-packages/DisplayCAL/wxSynthICCFrame.py",    │
│ line 1300, in update_trc_controls                                            │
│     self.profile_class_ctrl.GetStringSelection() ==                          │
│ self.profile_classes["scnr"]                                                 │
│ KeyError: 'scnr'                                                             │
└──────────────────────────────────────────────────────────────────────────────┘
Connection to 127.0.0.1:15411 failed: [Errno 111] Connection refused
Exiting displaycal-synthprofile
Ran application exit handlers
```

_Originally posted by @ctouz in https://github.com/eoyilmaz/displaycal-py3/issues/89#issuecomment-1114161921_

**Comment by eoyilmaz** [comment]
I can reproduce this error.

**Comment by ctouz** [comment]
Still an issue with main branch
works with develop branch

**Comment by eoyilmaz** [comment]
Yeah that's expected with the main branch, thank you for testing.
